# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f76c35f63f00b4b34a0a525b7b29d9f348903ecc224b64b410b36d59e65f35a132fa20c4e058ff5a477944f13956d6aafe24202ae9d46ae3de93fd008f6fb95

test:
  secret_key_base: fc61fd45cf886d275d00e36a85918c73302c73c9bafac2ae84123039fd715c9965cbb34c817c0352d7ddd16845417067e6c20aabc148e2dfd43b3dcb14767a90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
